#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2017, German Aerospace Center (DLR)
#
# This file is part of the development version of OUTPOST.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2017, Fabian Greif (DLR RY-AVS)

import os

Import('envGlobal')

envGlobal.RegisterStaticDependency('popl',
                                   link_libs=[],
                                   includepaths=os.path.abspath(
                                       'popl-1.3.0/include'),
                                   attributes=['header_only'])

extra_flags = {}
extra_flags['RemoveFromList'] = ['CXXFLAGS_warning', '-Wold-style-cast']

includepaths = os.path.abspath('serial/include')

files = envGlobal.RecursiveGlob('.cpp', searchdir="serial/src")

envGlobal.RegisterLibrary('serial', files, includepaths=includepaths,
                          env_flag_overrides=extra_flags)
