#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2017, Jan Sommer
# Copyright (c) 2017, Fabian Greif
# Copyright (c) 2024, Janosch Reinking
#
# This file is part of the Simple Interface Protocols (SIP) examples.
#
# It is supplied solely for the use by TUHH and HAW Hamburg
# in the frame of the PLUTO 1 flight mission.
# Distribution outside of the project or to people with no share in the PLUTO mission requires explicit permit granted by DLR-RY-AVS
# Contact jan-gerd.mess@dlr.de when in doubt.

import os

module = 'outpost_hal_posix'

Import('envGlobal')

# == TEST BUILD ==

unittest_deps = [
    module,
    'outpost_base_stubs',
    'googletest-local',
    'popl',
    ('dl', 'external'),
    ('util', 'external'),
]

files = envGlobal.RecursiveGlob('.cpp', searchdir='outpost')
files += [envGlobal.File('main.cpp')]

envGlobal.RegisterTest(module, files, unittest_deps)
