# Copyright (c) 2024, Jan-Gerd Mess
#
# This file is part of the Simple Interface Protocols (SIP) examples.
#
# It is supplied solely for the use by TUHH and HAW Hamburg
# in the frame of the PLUTO 1 flight mission.
# Distribution outside of the project or to people with no share in the PLUTO mission requires explicit permit granted by DLR-RY-AVS
# Contact jan-gerd.mess@dlr.de when in doubt.

import os
from os.path import join, abspath

envGlobal = SConscript('../SConscript.common', must_exist=1)

envGlobal.GenerateAllRegisteredLibraries(explain = True)

files = envGlobal.Glob("*.cpp")

envGlobal.Append(CPPPATH=abspath("."))

libdeps = [
    'outpost_hal_posix',
    'outpost_sip',
    'popl'
]

envGlobal.InsertDependenciesIntoEnv(libdeps)

prog_path = os.path.join("$BUILDPATH", envGlobal["program_name"])
prog = envGlobal.Program(prog_path, files)
inst = envGlobal.Install("../bin", prog)
envGlobal.Alias('build', inst)


