#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2014-2018, Fabian Greif
# Copyright (c) 2022, Tobias Pfeffer
#
# This file is part of the Simple Interface Protocols (SIP) examples.
#
# It is supplied solely for the use by TUHH and HAW Hamburg
# in the frame of the PLUTO 1 flight mission.
# Distribution outside of the project or to people with no share in the PLUTO mission requires explicit permit granted by DLR-RY-AVS
# Contact jan-gerd.mess@dlr.de when in doubt.

from SCons.Script import *


def generate(env, **kw):
    env.Tool('compiler_hosted_gcc')

    env.Append(CCFLAGS='--coverage')
    env.Append(LINKFLAGS='--coverage')

    env['CCFLAGS_optimize'] = [
        '-Og',
        '-fno-default-inline',
        '-fno-inline-functions',
        '-fno-inline',
    ]

    # Suppress warnings generated by gmock
    env.AppendUnique(CCFLAGS_warning='-Wno-unused-local-typedefs')

    # The C++ standard allows an implementation to omit creating a temporary
    # which is only used to initialize another object of the same type.
    # Specifying this option disables that optimization, and forces G++ to
    # call the copy constructor in all cases.
    env.AppendUnique(CXXFLAGS='-fno-elide-constructors')


def exists(env):
    return env.Detect('gcc')

