/*
 * Copyright (c) 2020-2021, Jan-Gerd Mess
 * Copyright (c) 2021, Jan Malburg
 * Copyright (c) 2024, Pieper, Pascal
 *
 * This file is part of the Simple Interface Protocols (SIP) examples.
 *
 * It is supplied solely for the use by TUHH and HAW Hamburg
 * in the frame of the PLUTO 1 flight mission.
 * Distribution outside of the project or to people with no share in the PLUTO mission requires explicit permit granted by DLR-RY-AVS
 * Contact jan-gerd.mess@dlr.de when in doubt.
 */

#ifndef OUTPOST_SWB_TYPES_H_
#define OUTPOST_SWB_TYPES_H_

#include <outpost/container/shared_buffer.h>

#include <stdint.h>

namespace outpost
{
namespace swb
{
/**
 * For detailed error handling and reporting, the following results can be generated by operations
 * within the SoftwareBus.
 * \ingroup swb
 */
enum class OperationResult : uint8_t
{
    success = 0,
    maxChannelsReached,
    noBufferAvailable,
    messageTooLong,
    sendFailed,
    noMessageAvailable,
    invalidState,
    invalidMessage,
    notFound
};

/**
 * Message is the fundamental datastructure that is passed around in the SoftwareBus.
 * \ingroup swb
 */
template <typename IDType>
struct Message
{
    IDType id;
    container::ConstSharedBufferPointer buffer;
};

}  // namespace swb
}  // namespace outpost

#endif /* OUTPOST_SWB_TYPES_H_ */
