#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2014, 2016-2017, 2019, Fabian Greif
# Copyright (c) 2022, Tobias Pfeffer
#
# This file is part of the Simple Interface Protocols (SIP) examples.
#
# It is supplied solely for the use by TUHH and HAW Hamburg
# in the frame of the PLUTO 1 flight mission.
# Distribution outside of the project or to people with no share in the PLUTO mission requires explicit permit granted by DLR-RY-AVS
# Contact jan-gerd.mess@dlr.de when in doubt.

import os

rootpath = os.path.abspath('../../../../')
envGlobal = Environment(
    toolpath=[os.path.join(rootpath, '../scons-build-tools/site_tools')],
    tools=[
        'compiler_hosted_llvm',
        'settings_buildpath',
        'utils_buildformat',
        'utils_buildsize'
    ],
    ENV=os.environ)

envGlobal['BASEPATH'] = os.path.abspath('.')
envGlobal['BUILDPATH'] = os.path.abspath(rootpath + 'build/rtos/test/posix')

envGlobal.SConscript(os.path.join(rootpath, 'SConscript.library'), exports='envGlobal')

env = envGlobal.Clone()

env.Append(CPPPATH=[
    '.',
    '../reference'
])
env.AppendUnique(LIBS=[
    'outpost_rtos',
    'outpost_smpc',
    'outpost_time',
    'outpost_utils',
])
env.Append(LIBPATH=['$BUILDPATH/lib'])

files  = env.Glob('*.cpp')
files += env.Glob('../reference/*.cpp')

program = env.Program('posix', files)

envGlobal.Alias('build', program)
envGlobal.Alias('install', env.Install('bin', program))

envGlobal.Default(['build', 'install'])
